spring:
  redis:
    cluster:
      nodes: 192.168.30.136:6379,192.168.30.136:6380,192.168.30.136:6381
      max-redirects: 3
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /